### ISSUE TITLE
Create React Boilerplate

### ISSUE THREAD

**Issue by andrewtremblay** [IndivisibleSomerville/its-our-call#11]
It has been decided offline that react.js will be our frontend of choice.

# Requirements 
Generate `its-our-call` react app in the `/frontend` directory.

**Comment by ethanbb** [comment]
I've seen create-react-app used for setup - any disadvantages to that you know about? It's for single-page applications only, which I think is what we want, right?

**Comment by andrewtremblay** [comment]
create-react-app is definitely the canonical way for generating React apps. I would suggest using that along with Webpack for bundling.
