### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by andrewtremblay** [IndivisibleSomerville/its-our-call#16]
Currently the design for the About page mentioned in the [nav menu issue](https://github.com/IndivisibleSomerville/its-our-call/issues/5) is missing.

<img width="228" alt="37187756-b3e47440-2319-11e8-96dc-6c38ddf257c7" src="https://user-images.githubusercontent.com/954150/37235094-d893c588-23c9-11e8-92e6-9905e19666a1.png">

# Requirements
- [ ] Design an About Page or remove the "About" from the nav menu design 
- [ ] Create an issue for frontend or update the nav menu issue.

**Comment by rlmayfield** [comment]
design complete
