### ISSUE TITLE
Filter Options

### ISSUE THREAD

**Issue by andrewtremblay** [IndivisibleSomerville/its-our-call#17]
Currently the design for the filter section mentioned in the [legislator list issue](https://github.com/IndivisibleSomerville/its-our-call/issues/8) is missing.

<img width="300" src="https://user-images.githubusercontent.com/954150/37235199-cb9fae86-23ca-11e8-9aba-cecd83e43d4a.png">

# Requirements

- [ ]  Design a filter section or remove it from the legislator list design
- [ ]  Create an issue for frontend or update [the legislator list issue](https://github.com/IndivisibleSomerville/its-our-call/issues/8).

**Comment by fleenshop** [comment]
@andrewtremblay The need for this, and what it would have to do, is something we're testing...

**Comment by rlmayfield** [comment]
removed from design, user testing showed this isn't needed for initial launch
