### ISSUE TITLE
Footer Component

### ISSUE THREAD

**Issue by andrewtremblay** [IndivisibleSomerville/its-our-call#18]
Currently the design for the footer component mentioned in the [Home Page issue](https://github.com/IndivisibleSomerville/its-our-call/issues/4) is missing.

<img width="200" src="https://user-images.githubusercontent.com/954150/37235278-61137e3e-23cb-11e8-881d-f4ee780d2387.png">

# Requirements
- [ ] Design an Footer component or remove the mentions of Footer from the home page design 
- [ ] Create an issue for frontend or update the home page issue.

**Comment by fleenshop** [comment]
@andrewtremblay So it is; noted.

**Comment by rlmayfield** [comment]
designed
