### ISSUE TITLE
Voting Record Page

### ISSUE THREAD

**Issue by andrewtremblay** [IndivisibleSomerville/its-our-call#19]
Currently the design for the Voting Record page mentioned in the [individual legislator issue](https://github.com/IndivisibleSomerville/its-our-call/issues/9) is missing.

<img width="280" src="https://user-images.githubusercontent.com/954150/37235558-8ebf665c-23cd-11e8-958d-267786135d53.png">

# Requirements
- [ ] Design the Voting Record Page or remove the "Voting Record" from the individual legislator design 
- [ ] Create an issue for frontend or update the individual legislator issue.

**Comment by rlmayfield** [comment]
Oh, this links to an external site, not sure which yet though. Where should we document where it links to?

**Comment by andrewtremblay** [comment]
I’d say update the design (or just add a comment) in the individual legislator issue and then close this one.

**Comment by fleenshop** [comment]
Added to Notes on the individual legislator issue.
