### ISSUE TITLE
Are User Profiles implied in the interface?

### ISSUE THREAD

**Issue by andrewtremblay** [IndivisibleSomerville/its-our-call#25]
Currently there are no mentions of user profiles in the interface, but the idea of tracking a user across sessions and devices might have been implied. This is particularly relevant to whatever is the expected behavior of Bookmarks (issue #24 ).

# Requirements
Identify the following needs:
- [x] Do we need user interaction history to be shared across devices (e.g. bookmarks)?
- [x] Do we need to identify users uniquely and/or permanently for analytics / backend purposes?
  - [x] Do we need to have login/registration flows for users if their data needs to properly persist?

**Comment by andrewtremblay** [comment]
If bookmarks and recently viewed politicians just need to be stored locally on the device then we might not need to keep references to users on the backend at all, which would greatly simplify the tech we need to build. 

@rlmayfield @fleenshop I think some of this was discussed offline already (we aren't concerned about  building user profiles right now) but it should be recorded here in the repo. 

@NCPtarmigan You should probably weigh in on this too (especially the second point).

**Comment by fleenshop** [comment]
@andrewtremblay @NCPtarmigan There's currently no user registration/user profiles on this site. (There will be on 5 Calls, associated with the data we're sent.) We thought we could have bookmarked legislators by cookie? I understand that means you won't see them on a new device without re-bookmarking.

**Comment by andrewtremblay** [comment]
Closing this issue after the tech check-up meeting. The approach to bookmarks will be either local storage or cookies. References to the user in the schema will be removed for now.
