### ISSUE TITLE
Match Header Navigation Bar to Wireframes

### ISSUE THREAD

**Issue by andrewtremblay** [IndivisibleSomerville/its-our-call#3]
Using the wireframe, begin to block out the top nav bar.

# Requirements 
- [ ]   **Nav Bar Title** : "It's our Call" : Clicking redirects to the home page.
- [ ]   **Nav Menu Button** : Clicking the button prompts a sliding menu overlay.
- [ ]   **Search Button** : Clicking prompts the search overlay.

# Other Notes 
This is a common component that will be used across the application.

The menu and search overlays can be non-interactive placeholders, those requirements are described in other issues.

# Design  
![wireframes-2018-03-08-navbar](https://user-images.githubusercontent.com/954150/37187172-09cd82dc-2317-11e8-8733-b7de25a257a9.png)

**Comment by andrewtremblay** [comment]
@ethanbb can this be your next issue?

**Comment by ethanbb** [comment]
Sure, I can work on this.

**Comment by andrewtremblay** [comment]
Thanks man!

**Comment by andrewtremblay** [comment]
@ethanbb Don't forget to close this issue if you think it's finished!
