### ISSUE TITLE
Add webpack

### ISSUE THREAD

**Issue by andrewtremblay** [IndivisibleSomerville/its-our-call#33]
Before deploying react to the frontend, we should be packaging it into a file (or cluster of files, depending on size).

# Requirements 
- [ ] Install some basic webpack devDependiencies
  - `webpack`
  - `dotenv-webpack`
  - `webpack-manifest-plugin`
  - `webpack-bundle-tracker`

- [ ] add webpack config details
  -  must have fileNamePattern `'[name]-' + utc date + '-[hash].js';`
  -  must have `ts-loader`, `style-loader/css-loader`,  & `file-loader` (for svgs/fonts)

**Comment by ethanbb** [comment]
Doesn't create-react-app already include webpack in its initial configuration? Can we just use `npm eject` to expose and customize webpack?

**Comment by andrewtremblay** [comment]
I forgot about that! I always eject and customize webpack from the start since I always customize it. 

I think customization is going to be inevitable (especially once we start getting deep into svgs), but we can move this to a lower priority issue until we hit those problems.

**Comment by andrewtremblay** [comment]
Closing as unnecessary.
