### ISSUE TITLE
Match Home to Wireframe

### ISSUE THREAD

**Issue by andrewtremblay** [IndivisibleSomerville/its-our-call#4]
Using the wireframe, begin to block out the home page (matching '/' in the router).

# Requirements
## Include the following interface sections
- [x] Header (placeholder is fine, the main implementation is handled in Issue #3)
- [x] Issue Section.
- [x] Legislator Section
- [x] Footer section

# Other Notes 
The data in the sections can be non-interactive placeholders, those will be handled in future issues.

# Design  
![wireframes-2018-03-08-home](https://user-images.githubusercontent.com/954150/37186710-cc7a926e-2314-11e8-9303-98a098ee5057.png)

**Comment by andrewtremblay** [comment]
@fleenshop @rlmayfield Can you add some more detail on what the top lorem ipsum does / is for? 
<img width="200" src="https://user-images.githubusercontent.com/954150/37235422-8005c76a-23cc-11e8-836f-90a631cab36c.png">

**Comment by fleenshop** [comment]
@andrewtremblay I think it's a little intro about what It's Our Call is/what it's for. @rlmayfield correct me if I'm wrong!

**Comment by andrewtremblay** [comment]
We have a Footer placeholder but I pretty much omitted it entirely. 
The rest of the code is here: https://github.com/IndivisibleSomerville/its-our-call/pull/32
