### ISSUE TITLE
Match Nav Menu to Wireframes

### ISSUE THREAD

**Issue by andrewtremblay** [IndivisibleSomerville/its-our-call#5]
Using the wireframe, begin to block out the top nav menu.

# Requirements 
- [ ]   **Issue List** : link : Clicking redirects to `/issues`.
- [ ]   **Legislators List** : link : Clicking redirects to `/legislators`.
- [ ]   **About** : link : Clicking redirects to `/about`.
- [ ]   **X** : button : Clicking dismisses the menu.
- [ ]   **Animation**:  Slide in and out on display/dismissal.
- [ ]   Clicking outside the focused menu (left part of the screen) dismisses the menu.

# Other Notes 
This is a common component that will be used across the application, might need to be implemented alongside issue #3 

The About page will need to be  designed (it is missing from the current wireframes).

# Design  
<img width="228" alt="wireframes-2018-03-08-nav-menu-expanded" src="https://user-images.githubusercontent.com/954150/37187756-b3e47440-2319-11e8-96dc-6c38ddf257c7.png">

**Comment by ethanbb** [comment]
### Updated wireframe: 

<img src="https://user-images.githubusercontent.com/8973825/38472778-207ca892-3b53-11e8-88c4-60910151b7b6.png" width="300" />
